# Generated by Django 3.1.3 on 2020-11-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmedCases', models.IntegerField()),
                ('newCases', models.IntegerField()),
                ('incidence', models.FloatField()),
                ('countyName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_database.county')),
            ],
        ),
    ]
