# Generated by Django 3.1.3 on 2020-11-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default='25-11-2020'),
        ),
    ]
