# Generated by Django 3.1.3 on 2020-11-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0002_dailyreport_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='date',
        ),
    ]
