# Generated by Django 3.1.3 on 2020-12-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0002_dailyreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='countyName',
            field=models.CharField(max_length=100),
        ),
    ]
