# Generated by Django 3.1.3 on 2020-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_database', '0004_auto_20201206_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(blank=True, default='2020-12-08'),
        ),
    ]
